# Generated by Django 4.0.3 on 2022-03-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('img', models.ImageField(upload_to='product')),
                ('dsc', models.TextField()),
                ('stock', models.IntegerField()),
                ('avail', models.BooleanField()),
                ('price', models.IntegerField()),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj1.category')),
            ],
        ),
    ]
