# Generated by Django 4.0.3 on 2022-03-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
